DROP DATABASE IF EXISTS test;

CREATE DATABASE test;

USE test;

CREATE TABLE test.books (
  ID INT NOT NULL AUTO_INCREMENT,
  BOOK_TITLE VARCHAR(255) NOT NULL,
  BOOK_AUTHOR VARCHAR(255) NOT NULL,
  BOOK_PRINTYEAR INT NOT NULL,
  BOOK_ISBN VARCHAR(255) NOT NULL,
  BOOK_DESCRIPTION VARCHAR(255) NOT NULL,
  BOOK_ALREADYREAD BOOLEAN NOT NULL,
  PRIMARY KEY (ID));

INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('1', 'A Brief History of Time', 'Stephen Hawking', '1998', 'fjh-er-567', 'NEW YORK TIMES BESTSELLER', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('2', 'A Heartbreaking Work of Staggering Genius', 'Dave Eggers', '2001', 'fjh-er-567', 'A Heartbreaking Work of Staggering Genius is an instant classic that will be read for decades to come.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('3', 'All the President''s Men', 'Bob Woodward', '1994', 'fjh-er-567', 'The full account of the Watergate scandal from the two Washington Post reporters who broke the story. ', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('4', 'Angela''s Ashes: A Memoir', 'Frank McCourt', '1999', 'fjh-er-567', 'A Pulitzer Prize–winning, #1 New York Times bestseller, Angela’s Ashes is Frank McCourt’s masterful memoir of his childhood in Ireland.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('5', 'Breath, Eyes, Memory', 'Edwidge Danticat', '1998', 'fjh-er-567', 'At an astonishingly young age, Edwidge Danticat has become one of our most celebrated new novelists, a writer who evokes the wonder, terror, and heartache of her native Haiti', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('6', 'Catch-22: 50th Anniversary Edition', 'Joseph Heller', '2011', 'fjh-er-567', 'This fiftieth-anniversary edition commemorates Joseph Heller’s masterpiece with a new introduction;; rare papers and photos; and much more.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('7', 'Charlie and the Chocolate Factory', 'Roald Dahl', '2001', 'fjh-er-567', 'Fifty years ago, Roald Dahl created a world that captured the imagination of millions of readers, and a boy who captured their hearts.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('8', 'Diary of a Wimpy Kid, Book 1', 'Jeff Kinney', '2007', 'fjh-er-567', 'Boys don’t keep diaries―or do they?The launch of an exciting and innovatively illustrated new series narrated by an unforgettable kid every family can relate to', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('9', 'Dune (Dune Chronicles, Book 1)', 'Frank Herbert', '2005', 'fjh-er-567', 'Frank Herbert’s epic masterpiece—a triumph of the imagination and the bestselling science fiction novel of all time.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('10', 'Fahrenheit 451', 'Ray Bradbury', '2012', 'fjh-er-567', 'Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 is a masterwork of twentieth-century literature set in a bleak, dystopian future.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('11', 'A Brief History of Time', 'Stephen Hawking', '1998', 'fjh-er-567', 'NEW YORK TIMES BESTSELLER', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('12', 'A Heartbreaking Work of Staggering Genius', 'Dave Eggers', '2001', 'fjh-er-567', 'A Heartbreaking Work of Staggering Genius is an instant classic that will be read for decades to come.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('13', 'All the President''s Men', 'Bob Woodward', '1994', 'fjh-er-567', 'The full account of the Watergate scandal from the two Washington Post reporters who broke the story. ', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('14', 'Angela''s Ashes: A Memoir', 'Frank McCourt', '1999', 'fjh-er-567', 'A Pulitzer Prize–winning, #1 New York Times bestseller, Angela’s Ashes is Frank McCourt’s masterful memoir of his childhood in Ireland.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('15', 'Breath, Eyes, Memory', 'Edwidge Danticat', '1998', 'fjh-er-567', 'At an astonishingly young age, Edwidge Danticat has become one of our most celebrated new novelists, a writer who evokes the wonder, terror, and heartache of her native Haiti', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('16', 'Catch-22: 50th Anniversary Edition', 'Joseph Heller', '2011', 'fjh-er-567', 'This fiftieth-anniversary edition commemorates Joseph Heller’s masterpiece with a new introduction;; rare papers and photos; and much more.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('17', 'Charlie and the Chocolate Factory', 'Roald Dahl', '2001', 'fjh-er-567', 'Fifty years ago, Roald Dahl created a world that captured the imagination of millions of readers, and a boy who captured their hearts.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('18', 'Diary of a Wimpy Kid, Book 1', 'Jeff Kinney', '2007', 'fjh-er-567', 'Boys don’t keep diaries―or do they?The launch of an exciting and innovatively illustrated new series narrated by an unforgettable kid every family can relate to', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('19', 'Dune (Dune Chronicles, Book 1)', 'Frank Herbert', '2005', 'fjh-er-567', 'Frank Herbert’s epic masterpiece—a triumph of the imagination and the bestselling science fiction novel of all time.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('20', 'Fahrenheit 451', 'Ray Bradbury', '2012', 'fjh-er-567', 'Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 is a masterwork of twentieth-century literature set in a bleak, dystopian future.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('21', 'A Brief History of Time', 'Stephen Hawking', '1998', 'fjh-er-567', 'NEW YORK TIMES BESTSELLER', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('22', 'A Heartbreaking Work of Staggering Genius', 'Dave Eggers', '2001', 'fjh-er-567', 'A Heartbreaking Work of Staggering Genius is an instant classic that will be read for decades to come.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('23', 'All the President''s Men', 'Bob Woodward', '1994', 'fjh-er-567', 'The full account of the Watergate scandal from the two Washington Post reporters who broke the story. ', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('24', 'Angela''s Ashes: A Memoir', 'Frank McCourt', '1999', 'fjh-er-567', 'A Pulitzer Prize–winning, #1 New York Times bestseller, Angela’s Ashes is Frank McCourt’s masterful memoir of his childhood in Ireland.', '0');
INSERT INTO test.books (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRINTYEAR, BOOK_ISBN, BOOK_DESCRIPTION, BOOK_ALREADYREAD) VALUES ('25', 'Breath, Eyes, Memory', 'Edwidge Danticat', '1998', 'fjh-er-567', 'At an astonishingly young age, Edwidge Danticat has become one of our most celebrated new novelists, a writer who evokes the wonder, terror, and heartache of her native Haiti', '0');
